name: update-public-registry-latest

on: 
  push:
    branches: 
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v1
      
    - name: Publish to Docker
      uses: zenato/docker-action@master
      with:
        username: tattletech
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tattletech/archive-telegram-bot
        tag: latest

    - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Updated Docker Registry for archive-telegram-bot:latest'
          SLACK_TITLE: 'update-registry-latest job complete'
          SLACK_COLOR: '#E56D67'
          SLACK_CHANNEL: notifications_rundeck